# NumPy (Numerical Python)

## What is NumPy?

NumPy (Numerical Python) is an open-source Python library used for numerical computing. It provides support for fast mathematical operations, multidimensional arrays, matrix manipulation, linear algebra, statistics, and many other scientific computing tasks.

NumPy is one of the most important libraries in Python and serves as the foundation for Data Science, Machine Learning, Artificial Intelligence, and Deep Learning.

## Why Do We Use NumPy?

- Fast numerical computations
- Efficient multidimensional arrays
- Less memory usage than Python lists
- Mathematical and statistical functions
- Matrix and linear algebra operations
- Random number generation
- Foundation of Pandas, Scikit-learn, TensorFlow, and PyTorch

In [1]:
import numpy as np #import numpy 


In [2]:
print(np.__version__)  # check version 


2.4.2


# Creating a NumPy Array

A NumPy array is the main data structure provided by the NumPy library. It stores elements of the same data type and allows efficient mathematical operations.

### Syntax

```python
np.array(iterable)
```

### Example

```python
arr = np.array([10, 20, 30, 40, 50])
```

In [3]:
np.array([10, 20, 30, 40, 50])


array([10, 20, 30, 40, 50])

# NumPy Arrays

A **NumPy Array** is the primary data structure of the NumPy library. It is also known as an **ndarray (N-dimensional Array)**. A NumPy array stores elements of the **same data type** and allows fast and efficient mathematical operations.

NumPy arrays can have different dimensions depending on how the data is organized.

## 1D (One-Dimensional) Array

A one-dimensional (1D) array contains elements in a single row. It is similar to a Python list.


In [4]:
# 1D Array
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

[10 20 30 40 50]


## 2D (Two-Dimensional) Array

A two-dimensional (2D) array contains rows and columns. It is similar to a table or matrix.



In [5]:
# 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## 3D (Three-Dimensional) Array

A three-dimensional (3D) array is a collection of multiple 2D arrays. It is commonly used for image processing, deep learning, and scientific computing.

In [6]:
# 3D Array   
# # 3D = List of 2D Arrays
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
arr1 = np.array([
    [[1, 2], [3, 4], [5, 6]],                    # 3D = List of 2D Arrays
    [[7, 8], [9, 10], [11, 12]]
])
print(arr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
arr2 = np.array([
    [[11, 22],[33, 44]],           
    [[55, 66], [77, 88]],
    [[99, 100], [111, 122]]                        # 3D = List of 2D Arrays
])

print(arr2)

[[[ 11  22]
  [ 33  44]]

 [[ 55  66]
  [ 77  88]]

 [[ 99 100]
  [111 122]]]


# Array Attributes

NumPy provides several built-in attributes that help us understand the properties of an array, such as its dimensions, shape, size, and data type.



## 1. ndim

The `ndim` attribute returns the number of dimensions (axes) of an array.



In [9]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(arr.ndim)

2


## 2. shape

The `shape` attribute returns the dimensions of an array in the form of `(rows, columns)`.



In [10]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr.shape)   # rowns and columns

(2, 3)


## 3. size

The `size` attribute returns the total number of elements present in the array.



In [11]:
arr = np.array([
    [5, 10, 15],
    [20, 25, 30]
])
print(arr.size)   #number tootal in aray

6


## 4. dtype

The `dtype` attribute returns the data type of the elements stored in the array.

In [12]:
np.array([10, 20, 30, 40]).dtype

dtype('int64')

# Array Creation Methods

NumPy provides several functions to create arrays quickly and efficiently.

## 1. np.array()

Creates an array from Python lists, tuples, or other iterable objects.



In [13]:

arr = np.array([5, 10, 15, 20, 25])

print(arr)

[ 5 10 15 20 25]


## 2. np.zeros()

Creates an array filled with zeros.

In [14]:
arr = np.zeros((3, 4))    # 3 rows or 4 columns

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 3. np.ones()

Creates an array filled with ones.

In [15]:
arr = np.ones((2, 5))

print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 4. np.arange()

Creates an array with evenly spaced values within a specified range.

In [16]:
arr = np.arange(5, 31, 5)

print(arr)

[ 5 10 15 20 25 30]


## 5. np.linspace()

Creates an array with a specified number of evenly spaced values between two numbers.

In [17]:
arr = np.linspace(0, 100, 11)
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


## 6. np.empty()

Creates an empty array. The values are uninitialized and may contain random data already present in memory

In [18]:
np.empty((2))

array([0.00000000e+000, 2.08600674e-308])

## 7. np.eye()

Creates an identity matrix with ones on the main diagonal and zeros elsewhere.

In [19]:

arr = np.eye(5)

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 8. np.full()

Creates an array where every element has the same specified value.

In [20]:
arr = np.full((3,3),4)

print(arr)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


## 9 np.logspace()

The `np.logspace()` function is used to create an array of numbers that are evenly spaced on a logarithmic scale.


In [21]:

arr = np.logspace(0, 10, 6)

print(arr)

[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08 1.e+10]


## 10.  np.random.seed()

The `np.random.seed()` function is used to initialize the random number generator with a fixed seed value.

Using the same seed always produces the same sequence of random numbers, making results reproducible.

In [22]:
array22=np.random.seed(67)   #np.random.seed() random numbers ka starting point set karta hai.
array22    #Same seed ⇒ same random numbers. Different seed ⇒ different random number

# Array Indexing
## What is Array Indexing?
Array indexing is the process of accessing one or more elements from a NumPy array using their index (position). Every element in a NumPy array has a unique index.
## Types of Indexing
### 1. Positive Indexing
Positive indexing starts from **0** and moves from left to right.


In [23]:

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[4])

10
20
30
50


In [24]:
fruits = np.array(["Apple", "Banana", "Mango", "Orange"])
print(fruits[0])
print(fruits[2])
print(fruits[3])

Apple
Mango
Orange


In [25]:
#2D array 
arr = np.array([
    [11, 22, 33],
    [44, 55, 66]
])

print(arr[0, 0])
print(arr[0, 2])
print(arr[1, 1])
print(arr[1, 2])

11
33
55
66


In [26]:
#3D array
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr[0, 0, 0])   # arr[layer, row, column]
print(arr[0, 1, 1])      
print(arr[1, 0, 1])
print(arr[1, 1, 0])

1
4
6
7


### 2. Negative Indexing
Negative indexing starts from **-1** and moves from right to left.

In [27]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[-1])
print(arr[-3])
print(arr[-5])

50
30
10


# Reshaping Arrays

Reshaping means changing the shape of an array without changing its data.

For example, a 1D array can be converted into a 2D array.

## Syntax

```python
array.reshape(rows, columns)
```

### Important Note

The total number of elements must remain the same.

For example:

- 6 elements → `(2, 3)`
- 6 elements → `(3, 2)`
- 6 elements → `(1, 6)`

All are valid because the total number of elements is 6.

In [28]:
#1D Array
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [29]:
# Reshape into 2D Array
arr_2d = arr.reshape(2, 3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


## Reshape into Different Shapes

The same 6 elements can be reshaped into different dimensions.

### 2 Rows and 3 Columns

```python
arr.reshape(2, 3)
```

### 3 Rows and 2 Columns

```python
arr.reshape(3, 2)
```

The total number of elements must remain the same.

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3))

print(arr.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# Flattening an Array

Flattening converts a multidimensional array into a one-dimensional array.

### Syntax

```python
array.flatten()
```

In [31]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat_arr = arr.flatten()

print(flat_arr)

[1 2 3 4 5 6]


# Copy vs View

## Copy

A copy creates a completely independent array.

Changes made to the copy do not affect the original array.

## View

A view creates a new way of looking at the same original data.

Changes made to the view can affect the original array.

In [32]:
arr = np.array([1, 2, 3, 4])

copy_arr = arr.copy()

copy_arr[0] = 100

print("Original Array:", arr)
print("Copy Array:", copy_arr)

Original Array: [1 2 3 4]
Copy Array: [100   2   3   4]


In [33]:
# View Example
arr = np.array([1, 2, 3, 4])

view_arr = arr.view()

view_arr[0] = 100

print("Original Array:", arr)
print("View Array:", view_arr)

Original Array: [100   2   3   4]
View Array: [100   2   3   4]


# NumPy Data Types

NumPy arrays have a specific data type called `dtype`.

The `dtype` tells us what type of data is stored in the array.

Common NumPy data types:

- `int`
- `float`
- `str`
- `bool`

In [34]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [35]:
arr = np.array([1, 2, 3], dtype="float")

print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


# Searching Arrays

NumPy provides the `np.where()` function to search for elements in an array.

### Syntax

```python
np.where(condition)
```

In [36]:
arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr == 30)

print(result)

(array([2]),)


In [37]:
# Find Values Greater Than 25
arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr > 25)

print(result)

(array([2, 3, 4]),)


# Universal Functions (ufuncs)

Universal Functions, also called **ufuncs**, perform mathematical operations element by element on NumPy arrays.

Examples:

- `np.sqrt()` → Square root
- `np.exp()` → Exponential
- `np.sin()` → Sine
- `np.cos()` → Cosine

In [38]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))

[1. 2. 3. 4.]


# Statistical Functions

NumPy provides statistical functions to analyze numerical data.

Common statistical functions:

- `np.mean()` → Average
- `np.median()` → Middle value
- `np.std()` → Standard deviation
- `np.min()` → Minimum value
- `np.max()` → Maximum value
- `np.sum()` → Sum of values

In [39]:
marks = np.array([60, 70, 80, 90, 100])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
print("Sum:", np.sum(marks))

Mean: 80.0
Median: 80.0
Standard Deviation: 14.142135623730951
Minimum: 60
Maximum: 100
Sum: 400


# Linear Algebra (Basic)

NumPy provides functions for basic linear algebra operations.

Common operations:

- Dot Product
- Matrix Multiplication
- Transpose

### Dot Product

The dot product multiplies corresponding values and adds the results.

In [40]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

result = np.dot(a, b)

print(result)

32


In [41]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.dot(a, b)

print(result)

[[19 22]
 [43 50]]


In [42]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]
